### ISSUE TITLE
Error loading napp amlight/coloring

### ISSUE THREAD

**Issue by italovalcy** [amlight/coloring#7]
Hi,

When loading the amlight/coloring napp, the following exception is raised:
```
2021-02-11 18:31:05,170 - INFO [kytos.napps] (coloring) Running NApp: <Main(coloring, started 139726963078912)>
Exception in thread coloring:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f14d413bb70>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /api/kytos/topology/v3/links (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f14d413bb70>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/kytos/core/napps/base.py", line 247, in run
    self.execute()
  File "//var/lib/kytos/napps/amlight/coloring/main.py", line 42, in execute
    response = requests.get(settings.TOPOLOGY_URL)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8181): Max retries exceeded with url: /api/kytos/topology/v3/links (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f14d413bb70>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Steps to reproduce:
1. Use the Kytos nightly docker image
2. Enable a couple of napps:
```
 python3 -m pip install -e git+https://github.com/kytos/storehouse#egg=kytos-storehouse
 python3 -m pip install -e git+https://github.com/kytos/of_core#egg=kytos-of_core
 python3 -m pip install -e git+https://github.com/kytos/flow_manager#egg=kytos-flow_manager
 python3 -m pip install -e git+https://github.com/kytos/topology#egg=kytos-topology
 python3 -m pip install -e git+https://github.com/kytos/of_lldp#egg=kytos-of_lldp
 python3 -m pip install -e git+https://github.com/kytos/pathfinder#egg=kytos-pathfinder
 python3 -m pip install -e git+https://github.com/kytos/mef_eline#egg=kytos-mef_eline
 python3 -m pip install -e git+https://github.com/amlight/coloring#egg=amlight-coloring
 python3 -m pip install -e git+https://github.com/amlight/sdntrace#egg=amlight-sdntrace
```
3. restart kytos with the console enabled:
```
kytosd -f -E
```

**Comment by italovalcy** [comment]
This seems to be caused because the coloring napp relies on the topology API when booting up: https://github.com/amlight/coloring/blob/master/main.py#L40-L48

However, one should notice that during Kytos startup, the topology API server or even the topology napp may not be ready when called through the execute() function from another napp. Furthermore, the topology already generate events of topology.updated when Kytos finishes the startup process and this events are already handled by amlight/coloring.

As far as I could understand, it looks like getting the topology on initialization through the method amlight/coloring.execute() is redundant (it will be informed when the topology gets ready) and create this issue.
